services:
  backend:
    build: ./agent
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "8000"
    networks:
      - app-net
    

  frontend:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - BACKEND_INTERNAL_URL=http://backend:8000
    networks:
      - app-net
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  app-net:
    driver: bridge